services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: scaler-journey-api:dev

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        VITE_API_KEY: ${VITE_API_KEY}
        VITE_API_BASE_URL: ""

    image: scaler-journey-app:dev

    environment:
      DOMAIN_NAME: localhost

    depends_on:
      api:
        condition: service_healthy