services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: scaler-journey-api:dev

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: scaler-journey-app:dev