// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyTracker.Api.Data;

#nullable disable

namespace StudyTracker.Api.Migrations
{
    [DbContext(typeof(StudyTrackerContext))]
    [Migration("20260819133000_AddKnowledgeAtlasTables")]
    partial class AddKnowledgeAtlasTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Existing & New Models built in snapshot
#pragma warning restore 612, 618
        }
    }
}
